version: "3.8"

services:
  webserver:
    build: 
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      # Environment variables for connecting to db1 on the host machine
      DB1_HOST: host.docker.internal  # Use your host machine's IP if host.docker.internal doesn't work
      DB1_NAME: yummy_bar_new
      DB1_USER: root
      DB1_PASSWORD: root
      
      # Environment variables for connecting to db2 on the host machine
      DB2_HOST: host.docker.internal  # Use your host machine's IP if host.docker.internal doesn't work
      DB2_NAME: yummy-bar
      DB2_USER: root
      DB2_PASSWORD: root
      
      # Application URL
      SITE_URL: http://localhost:8080
